import { Button } from "../utils/types"

const useButtonsValues = (isMobile: boolean): Button[] => {
  if (!isMobile) {
    return [
      { value: "sin", label: "Sin", color: "white" },
      { value: "pi", icon: "pi", color: "white", label: "pi" },
      { value: "e", label: "e", color: "white" },
      { value: "clear", label: "CE", color: "main" },
      { value: "square", label: "x²", color: "white" },
      { value: "cos", label: "Cos", color: "white" },
      { value: "pow", icon: "pow", color: "white", label: "pow" },
      { value: "√", icon: "radical", color: "white", label: "radical" },
      { value: "%", icon: "percentage", color: "white", label: "percentage" },
      { value: "/", icon: "division", color: "white", label: "division" },
      { value: "tan", label: "Tan", color: "white" },
      { value: "7", label: "7", color: "dark" },
      { value: "8", label: "8", color: "dark" },
      { value: "9", label: "9", color: "dark" },
      { value: "*", icon: "times", color: "white", label: "times" },
      { value: "abs", icon: "absolute", color: "white", label: "absolute" },
      { value: "4", label: "4", color: "dark" },
      { value: "5", label: "5", color: "dark" },
      { value: "6", label: "6", color: "dark" },
      { value: "-", icon: "minus", color: "white", label: "minus" },
      { value: "!", label: "n!", color: "white" },
      { value: "1", label: "1", color: "dark" },
      { value: "2", label: "2", color: "dark" },
      { value: "3", label: "3", color: "dark" },
      { value: "+", icon: "plus", color: "white", label: "plus" },
      { value: "log", label: "Log", color: "white" },
      { value: "()", icon: "parentesis", color: "white", label: "parentesis" },
      { value: "0", label: "0", color: "dark" },
      { value: ".", label: ".", color: "white" },
      { value: "result", icon: "result", color: "main", label: "result" },
    ]
  }
  
  return [
    { value: "sin", label: "Sin", color: "white" },
    { value: "cos", label: "Cos", color: "white" },
    { value: "tan", label: "Tan", color: "white" },
    { value: "clear", label: "CE", color: "main" },
    { value: "pi", icon: "pi", color: "white", label: "pi" },
    { value: "e", label: "e", color: "white" },
    { value: "!", label: "n!", color: "white" },
    { value: "log", label: "Log", color: "white" },
    { value: "pow", icon: "pow", color: "white", label: "pow" },
    { value: "abs", icon: "absolute", color: "white", label: "absolute" },
    { value: "√", icon: "radical", color: "white", label: "radical" },
    { value: "square", label: "x²", color: "white" },
    { value: "(", icon: "open-parentesis", color: "white", label: "open-parentesis" },
    { value: ")", icon: "close-parentesis", color: "white", label: "close-parentesis" },
    { value: "%", icon: "percentage", color: "white", label: "percentage" },
    { value: "/", icon: "division", color: "white", label: "division" },
    { value: "7", label: "7", color: "dark" },
    { value: "8", label: "8", color: "dark" },
    { value: "9", label: "9", color: "dark" },
    { value: "*", icon: "times", color: "white", label: "times" },
    { value: "4", label: "4", color: "dark" },
    { value: "5", label: "5", color: "dark" },
    { value: "6", label: "6", color: "dark" },
    { value: "-", icon: "minus", color: "white", label: "minus" },
    { value: "1", label: "1", color: "dark" },
    { value: "2", label: "2", color: "dark" },
    { value: "3", label: "3", color: "dark" },
    { value: "+", icon: "plus", color: "white", label: "plus" },
    { value: "toggle", icon: "toogle-sign", color: "white", label: "toogle-sign" },
    { value: "0", label: "0", color: "dark" },
    { value: ".", label: ".", color: "white" },
    { value: "result", icon: "result", color: "main", label: "result" },
  ]
}

export default useButtonsValues